### ISSUE TITLE
HELICS version issue

### ISSUE THREAD

**Issue by akshaykj92** [GMLC-TDC/helics-cli#30]
I am using a windows machine to run multiple federates using HELICS-CLI. The issue I am seeing is when I first setup my anaconda environment using python 3.6 and HELICS and HELICS-apps versions 2.6.0, my code doesn't execute and I get the following error:

Error: Process broker has failed, killing other processes
Exception in thread Thread-1:
Traceback (most recent call last):
    File "c:\...\anaconda3\envs\pythonproject\lib\threading.py", line 916, in _bootstrap_inner
self.run()
    File "c:\...\anaconda3\envs\pythonproject\lib\site-packages\helics_cli\status_checker.py", line 43, in run helics_cli.exceptions.HELICSRuntimeError: Error has occured 
    
Then when I move to HELICS and HELICS-Apps versions 2.4.2 the error gets fixed and code works without any modifications. After this even if I move back to versions 2.6.0 again the code keeps working.

**Comment by kdheepak** [comment]
Is there a broker.log file in that folder? Can you share the contents of that folder?

**Comment by akshaykj92** [comment]
@kdheepak All the log files including the broker and federate logs were empty.

**Comment by kdheepak** [comment]
@akshaykj92 how many federates do you have? Can you run it without helics-cli to see if you still have this issue?

cc @phlptp.

**Comment by akshaykj92** [comment]
I can run it with just two federates but will have to modify my code slightly, will get back as soon as I have done that. However, I believe I will not have the issue as it was resolved after moving to versions 2.4.2 and then back again to 2.6.0

**Comment by kdheepak** [comment]
I'm asking because if you are able to run it without helics-cli the error message might be more obvious. 

Alternatively, if you can share your code, I will be able to test it on my end.

**Comment by akshaykj92** [comment]
Sure Dheepak, I will set up an example and share the code with you separately.
