### ISSUE TITLE
helics-cli source code "nimble build" error

### ISSUE THREAD

**Issue by lzheng28** [GMLC-TDC/helics-cli#36]
Hello, I'm trying to compile the source code using "nimble build", but it didn't run successfully, and I received the following error:

```
(py3.7-helics-2.2.0) lei@lei-VirtualBox:~/software/helics-cli$ nimble build
  Verifying dependencies for helics_cli@0.4.3
      Info: Dependency on cligen@any version already satisfied
  Verifying dependencies for cligen@1.5.0
      Info: Dependency on shlex@any version already satisfied
  Verifying dependencies for shlex@0.1.0
      Info: Dependency on jester@any version already satisfied
  Verifying dependencies for jester@0.5.0
      Info: Dependency on httpbeast@>= 0.2.2 already satisfied
  Verifying dependencies for httpbeast@0.2.2
      Info: Dependency on https://github.com/timotheecour/asynctools@#pr_fix_compilation already satisfied
  Verifying dependencies for asynctools@#pr_fix_compilation
      Info: Dependency on https://github.com/timotheecour/asynctools@#pr_fix_compilation already satisfied
  Verifying dependencies for asynctools@#pr_fix_compilation
      Info: Dependency on https://github.com/GMLC-TDC/helics.nim@#head already satisfied
  Verifying dependencies for helics@#head
   Building helics_cli/helics_cli using c backend
/home/lei/software/helics-cli/src/utils.nim(2, 6) Warning: imported and not used: 'os' [UnusedImport]
/home/lei/software/helics-cli/src/utils.nim(3, 8) Warning: imported and not used: 'httpclient' [UnusedImport]
/home/lei/software/helics-cli/src/utils.nim(16, 8) Warning: imported and not used: 'strtabs' [UnusedImport]
/home/lei/software/helics-cli/src/utils.nim(5, 8) Warning: imported and not used: 'mimetypes' [UnusedImport]
/home/lei/software/helics-cli/src/utils.nim(6, 8) Warning: imported and not used: 'os' [UnusedImport]
/home/lei/software/helics-cli/src/utils.nim(14, 8) Warning: imported and not used: 'threadpool' [UnusedImport]
/home/lei/software/helics-cli/src/utils.nim(8, 8) Warning: imported and not used: 'sequtils' [UnusedImport]
/home/lei/software/helics-cli/src/utils.nim(9, 8) Warning: imported and not used: 'shlex' [UnusedImport]
/home/lei/software/helics-cli/src/utils.nim(10, 8) Warning: imported and not used: 'strformat' [UnusedImport]
/home/lei/software/helics-cli/src/utils.nim(11, 8) Warning: imported and not used: 'strutils' [UnusedImport]
/home/lei/software/helics-cli/src/utils.nim(12, 8) Warning: imported and not used: 'sugar' [UnusedImport]
/home/lei/software/helics-cli/src/validate.nim(14, 8) Warning: imported and not used: 'threadpool' [UnusedImport]
/home/lei/software/helics-cli/src/validate.nim(3, 8) Warning: imported and not used: 'httpclient' [UnusedImport]
/home/lei/software/helics-cli/src/validate.nim(13, 8) Warning: imported and not used: 'terminal' [UnusedImport]
/home/lei/software/helics-cli/src/validate.nim(5, 8) Warning: imported and not used: 'mimetypes' [UnusedImport]
/home/lei/software/helics-cli/src/validate.nim(16, 8) Warning: imported and not used: 'strtabs' [UnusedImport]
/home/lei/software/helics-cli/src/validate.nim(7, 8) Warning: imported and not used: 'osproc' [UnusedImport]
/home/lei/software/helics-cli/src/validate.nim(8, 8) Warning: imported and not used: 'sequtils' [UnusedImport]
/home/lei/software/helics-cli/src/validate.nim(9, 8) Warning: imported and not used: 'shlex' [UnusedImport]
/home/lei/software/helics-cli/src/validate.nim(15, 8) Warning: imported and not used: 'streams' [UnusedImport]
/home/lei/software/helics-cli/src/validate.nim(11, 8) Warning: imported and not used: 'strutils' [UnusedImport]
/home/lei/software/helics-cli/src/validate.nim(12, 8) Warning: imported and not used: 'sugar' [UnusedImport]
/home/lei/software/helics-cli/src/run.nim(1, 8) Warning: imported and not used: 'httpclient' [UnusedImport]
/home/lei/software/helics-cli/src/run.nim(13, 8) Warning: imported and not used: 'streams' [UnusedImport]
/home/lei/software/helics-cli/src/run.nim(3, 8) Warning: imported and not used: 'mimetypes' [UnusedImport]
/home/lei/software/helics-cli/src/run.nim(14, 8) Warning: imported and not used: 'strtabs' [UnusedImport]
/home/lei/software/helics-cli/src/run.nim(11, 8) Warning: imported and not used: 'terminal' [UnusedImport]
/home/lei/software/helics-cli/src/run.nim(9, 8) Warning: imported and not used: 'strutils' [UnusedImport]
/home/lei/software/helics-cli/src/run.nim(7, 8) Warning: imported and not used: 'shlex' [UnusedImport]
/home/lei/software/helics-cli/src/observe.nim(78, 47) Error: 'pub' is of type <lent TaintedString> which cannot be captured as it would violate memory safety, declared here: /home/lei/software/helics-cli/src/observe.nim(77, 9); using '-d:nimWorkaround14447' helps in some cases
       Tip: 17 messages have been suppressed, use --verbose to show them.
     Error: Build failed for package: helics_cli
        ... Execution failed with exit code 1
        ... Command: /usr/bin/nim c --colors:on --noNimblePath -d:NimblePkgVersion=0.4.3 --path:/home/lei/.nimble/pkgs/cligen-1.5.0 --path:/home/lei/.nimble/pkgs/shlex-0.1.0 --path:/home/lei/.nimble/pkgs/jester-0.5.0 --path:/home/lei/.nimble/pkgs/httpbeast-0.2.2 --path:'/home/lei/.nimble/pkgs/asynctools-#pr_fix_compilation' --path:'/home/lei/.nimble/pkgs/asynctools-#pr_fix_compilation' --path:'/home/lei/.nimble/pkgs/helics-#head' --hints:off -o:/home/lei/software/helics-cli/bin/helics_cli /home/lei/software/helics-cli/helics_cli.nim
```

And I also use the method [pip install git+git://github.com/GMLC-TDC/helics-cli.git@master](https://docs.helics.org/en/latest/user-guide/value_federates.html?highlight=gridlab#example-1a-basic-transmission-and-distribution-powerflow) to install helics-cli, but it show the following error:

```
(py3.7-helics-2.2.0) lei@lei-VirtualBox:~/Desktop/Example_1a$ pip install git+git://github.com/GMLC-TDC/helics-cli.git@master
Collecting git+git://github.com/GMLC-TDC/helics-cli.git@master
  Cloning git://github.com/GMLC-TDC/helics-cli.git (to revision master) to /tmp/pip-req-build-jsce076v
  Running command git clone -q git://github.com/GMLC-TDC/helics-cli.git /tmp/pip-req-build-jsce076v
    ERROR: Command errored out with exit status 1:
     command: /home/lei/anaconda3/envs/py3.7-helics-2.2.0/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-jsce076v/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-jsce076v/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-_iy68k3_
         cwd: /tmp/pip-req-build-jsce076v/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/lei/anaconda3/envs/py3.7-helics-2.2.0/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-jsce076v/setup.py'
    ----------------------------------------
WARNING: Discarding git+git://github.com/GMLC-TDC/helics-cli.git@master. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
Could you please help me solve this problem? Thank you so much, I'm quite confused about the error.

**Comment by kdheepak** [comment]
We are moving to using Python instead of Nim. Check out the `python-master` branch for now. The following should work:

```bash
 pip install git+git://github.com/GMLC-TDC/helics-cli.git@python-master
```

**Comment by lzheng28** [comment]
Yes, it works, thank you so much.

**Comment by lzheng28** [comment]
> We are moving to using Python instead of Nim. Check out the `python-master` branch for now. The following should work:
> 
> ```shell
>  pip install git+git://github.com/GMLC-TDC/helics-cli.git@python-master
> ```

Yes, it works, thank you so much
