### ISSUE TITLE
An error when running helics-cli (0.5.0) + helics-2.7.1 in an example.

### ISSUE THREAD

**Issue by lzheng28** [GMLC-TDC/helics-cli#46]
When I try to run the example [here](https://docs.helics.org/en/latest/user-guide/value_federates.html?highlight=example#example-1a-basic-transmission-and-distribution-powerflow), it will has an error in the following
`Traceback (most recent call last):
  File "Transmission_simulator.py", line 81, in <module>
    fed = h.helicsCreateValueFederateFromConfig("Transmission_json.json")
  File "/home/lei/anaconda3/envs/helics-cli/lib/python3.7/site-packages/helics/capi.py", line 3137, in helicsCreateValueFederateFromConfig
    raise HelicsException("[" + str(err.error_code) + "] " + ffi.string(err.message).decode())
helics.capi.HelicsException: [-3] --loglevel: Check  value in {connections->,data->,debug->,error->,interfaces->,no_print->,none->,summary->,timing->,trace->,warning->} OR {,,,,,,,,,,} FAILED
`
But when I use helics-cli(0.1.0) + helics-2.6.1, it will work fine. I don't know where the problem is. Is there any hint for me to solve this? Thank you so much!

**Comment by kdheepak** [comment]
What version of helics are you using?

**Comment by lzheng28** [comment]
I use helics v2.7.1 with python, and GridLAB-D with helics is v2.6.1. but if I use helics v2.6.1, it will have an error in the following
`(helics-cli) lei@lei-VirtualBox:~/Desktop/HELICS-Examples/user_guide_examples/to_sort/Example_1a$ helics run --path cosim_runner_1a.json 
Traceback (most recent call last):
  File "/home/lei/anaconda3/envs/helics-cli/bin/helics", line 5, in <module>
    from helics_cli.cli import cli
  File "/home/lei/anaconda3/envs/helics-cli/lib/python3.7/site-packages/helics_cli/cli.py", line 18, in <module>
    from . import observer
  File "/home/lei/anaconda3/envs/helics-cli/lib/python3.7/site-packages/helics_cli/observer.py", line 23, in <module>
    broker: h.HelicsBroker
AttributeError: module 'helics' has no attribute 'HelicsBroker'
`
