### ISSUE TITLE
Error when running PIP Install

### ISSUE THREAD

**Issue by StormsHalted** [GMLC-TDC/helics-cli#59]
Hi,

I get this error when trying to run:

pip install git+git://github.com/GMLC-TDC/helics-cli.git@main

Collecting git+git://github.com/GMLC-TDC/helics-cli.git@main
  Cloning git://github.com/GMLC-TDC/helics-cli.git (to revision main) to /tmp/pip-req-build-47zahdil
  Running command git clone -q git://github.com/GMLC-TDC/helics-cli.git /tmp/pip-req-build-47zahdil
  fatal: remote error:
    The unauthenticated git protocol on port 9418 is no longer supported.
  Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
WARNING: Discarding git+git://github.com/GMLC-TDC/helics-cli.git@main. Command errored out with exit status 128: git clone -q git://github.com/GMLC-TDC/helics-cli.git /tmp/pip-req-build-47zahdil Check the logs for full command output.
ERROR: Command errored out with exit status 128: git clone -q git://github.com/GMLC-TDC/helics-cli.git /tmp/pip-req-build-47zahdil Check the logs for full command output.

Any solutions?

**Comment by kdheepak** [comment]
I think this is because it appears that pip install from GitHub isn’t supported anymore. I’ll share a workaround when I’m back at my computer and I’m able to look into it more.

**Comment by kdheepak** [comment]
This should work:

```bash
pip install git+https://github.com/GMLC-TDC/helics-cli.git@main
```

**Comment by qhuang0411** [comment]
I work with a MacOS with m1 chip. I followed the command given above, but still got the following error. Any suggestion? 

----------------
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [118 lines of output]
      ERROR: Exception:
      Traceback (most recent call last):
        File "/Users/qhuang/.pyenv/versions/3.7.13/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
          status = run_func(*args)
        File "/Users/qhuang/.pyenv/versions/3.7.13/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
          return func(self, options, args)
        File "/Users/qhuang/.pyenv/versions/3.7.13/lib/python3.7/site-packages/pip/_internal/commands/wheel.py", line 145, in run
          requirement_set = resolver.resolve(reqs, check_supported_wheels=True)
        File "/Users/qhuang/.pyenv/versions/3.7.13/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
          collected.requirements, max_rounds=try_to_avoid_resolution_too_deep
        File "/Users/qhuang/.pyenv/versions/3.7.13/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
          state = resolution.resolve(requirements, max_rounds=max_rounds)
        File "/Users/qhuang/.pyenv/versions/3.7.13/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 348, in resolve
          self._add_to_criteria(self.state.criteria, r, parent=None)
        File "/Users/qhuang/.pyenv/versions/3.7.13/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
          if not criterion.candidates:
        File "/Users/qhuang/.pyenv/versions/3.7.13/lib/python3.7/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
          return bool(self._sequence)
        File "/Users/qhuang/.pyenv/versions/3.7.13/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
          return any(self)
        File "/Users/qhuang/.pyenv/versions/3.7.13/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
          return (c for c in iterator if id(c) not in self._incompatible_ids)
        File "/Users/qhuang/.pyenv/versions/3.7.13/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
          candidate = func()
        File "/Users/qhuang/.pyenv/versions/3.7.13/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 220, in _make_candidate_from_link
          version=version,
        File "/Users/qhuang/.pyenv/versions/3.7.13/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 294, in __init__
          version=version,
        File "/Users/qhuang/.pyenv/versions/3.7.13/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 158, in __init__
          self.dist = self._prepare()
        File "/Users/qhuang/.pyenv/versions/3.7.13/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 227, in _prepare
          dist = self._prepare_distribution()
        File "/Users/qhuang/.pyenv/versions/3.7.13/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 299, in _prepare_distribution
          return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
        File "/Users/qhuang/.pyenv/versions/3.7.13/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 487, in prepare_linked_requirement
          return self._prepare_linked_requirement(req, parallel_builds)
        File "/Users/qhuang/.pyenv/versions/3.7.13/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 560, in _prepare_linked_requirement
          self.build_isolation,
        File "/Users/qhuang/.pyenv/versions/3.7.13/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 58, in _get_prepared_distribution
          abstract_dist.prepare_distribution_metadata(finder, build_isolation)
        File "/Users/qhuang/.pyenv/versions/3.7.13/lib/python3.7/site-packages/pip/_internal/distributions/sdist.py", line 45, in prepare_distribution_metadata
          self._install_build_reqs(finder)
        File "/Users/qhuang/.pyenv/versions/3.7.13/lib/python3.7/site-packages/pip/_internal/distributions/sdist.py", line 104, in _install_build_reqs
          build_reqs = self._get_build_requires_wheel()
        File "/Users/qhuang/.pyenv/versions/3.7.13/lib/python3.7/site-packages/pip/_internal/distributions/sdist.py", line 81, in _get_build_requires_wheel
          return backend.get_requires_for_build_wheel()
        File "/Users/qhuang/.pyenv/versions/3.7.13/lib/python3.7/site-packages/pip/_vendor/pep517/wrappers.py", line 173, in get_requires_for_build_wheel
          'config_settings': config_settings
        File "/Users/qhuang/.pyenv/versions/3.7.13/lib/python3.7/site-packages/pip/_vendor/pep517/wrappers.py", line 332, in _call_hook
          raise BackendUnavailable(data.get('traceback', ''))
      pip._vendor.pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
        File "/Users/qhuang/.pyenv/versions/3.7.13/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 89, in _build_backend
          obj = import_module(mod_path)
        File "/Users/qhuang/.pyenv/versions/3.7.13/lib/python3.7/importlib/__init__.py", line 127, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
        File "<frozen importlib._bootstrap>", line 983, in _find_and_load
        File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
        File "<frozen importlib._bootstrap>", line 983, in _find_and_load
        File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 728, in exec_module
        File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
        File "/private/var/folders/97/vgkgwbcj3yx61tdn7p3yt8sc0000gp/T/pip-build-env-39aeq9sm/overlay/lib/python3.7/site-packages/setuptools/__init__.py", line 18, in <module>
          from setuptools.dist import Distribution
        File "/private/var/folders/97/vgkgwbcj3yx61tdn7p3yt8sc0000gp/T/pip-build-env-39aeq9sm/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 38, in <module>
          from setuptools import windows_support
        File "/private/var/folders/97/vgkgwbcj3yx61tdn7p3yt8sc0000gp/T/pip-build-env-39aeq9sm/overlay/lib/python3.7/site-packages/setuptools/windows_support.py", line 2, in <module>
          import ctypes
        File "/Users/qhuang/.pyenv/versions/3.7.13/lib/python3.7/ctypes/__init__.py", line 7, in <module>
          from _ctypes import Union, Structure, Array
      ModuleNotFoundError: No module named '_ctypes'
      
      
      Edit mplsetup.cfg to change the build options; suppress output with --quiet.
      
      BUILDING MATPLOTLIB
            python: yes [3.7.13 (default, May 23 2022, 16:09:17)  [Clang 13.1.6
                        (clang-1316.0.21.2.5)]]
          platform: yes [darwin]
             tests: no  [skipping due to configuration]
            macosx: yes [installing]
      
      /Users/qhuang/.pyenv/versions/3.7.13/lib/python3.7/site-packages/setuptools/installer.py:30: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        SetuptoolsDeprecationWarning,
      Traceback (most recent call last):
        File "/Users/qhuang/.pyenv/versions/3.7.13/lib/python3.7/site-packages/setuptools/installer.py", line 82, in fetch_build_egg
          subprocess.check_call(cmd)
        File "/Users/qhuang/.pyenv/versions/3.7.13/lib/python3.7/subprocess.py", line 363, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/Users/qhuang/.pyenv/versions/3.7.13/bin/python3.7', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/97/vgkgwbcj3yx61tdn7p3yt8sc0000gp/T/tmpwqvh5opa', '--quiet', 'numpy>=1.17']' returned non-zero exit status 2.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/97/vgkgwbcj3yx61tdn7p3yt8sc0000gp/T/pip-install-4rhrb_pz/matplotlib_0c1307b27e964ce1998483d8ac5eaaed/setup.py", line 349, in <module>
          "sdist": Sdist,
        File "/Users/qhuang/.pyenv/versions/3.7.13/lib/python3.7/site-packages/setuptools/__init__.py", line 86, in setup
          _install_setup_requires(attrs)
        File "/Users/qhuang/.pyenv/versions/3.7.13/lib/python3.7/site-packages/setuptools/__init__.py", line 80, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/Users/qhuang/.pyenv/versions/3.7.13/lib/python3.7/site-packages/setuptools/dist.py", line 879, in fetch_build_eggs
          replace_conflicting=True,
        File "/Users/qhuang/.pyenv/versions/3.7.13/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
          replace_conflicting=replace_conflicting
        File "/Users/qhuang/.pyenv/versions/3.7.13/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1075, in best_match
          return self.obtain(req, installer)
        File "/Users/qhuang/.pyenv/versions/3.7.13/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1087, in obtain
          return installer(requirement)
        File "/Users/qhuang/.pyenv/versions/3.7.13/lib/python3.7/site-packages/setuptools/dist.py", line 956, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "/Users/qhuang/.pyenv/versions/3.7.13/lib/python3.7/site-packages/setuptools/installer.py", line 84, in fetch_build_egg
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['/Users/qhuang/.pyenv/versions/3.7.13/bin/python3.7', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/97/vgkgwbcj3yx61tdn7p3yt8sc0000gp/T/tmpwqvh5opa', '--quiet', 'numpy>=1.17']' returned non-zero exit status 2.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by StormsHalted** [comment]
Morning @kdheepak 

The script works fine now. I will thereafter test the helics CLI and  let you know if their are any issues.
