### ISSUE TITLE
Issue when broker=false on Windows

### ISSUE THREAD

**Issue by mnblonsky** [GMLC-TDC/helics-cli#6]
I get the following error when running helics client on Windows. It only occurs when I set "broker": false in the config.json file. Setting "broker" to true works just fine.

I'm using helics 2.0.0 and helics-runner 0.1.0a0. Let me know if I can give any more info.

Traceback (most recent call last):
  File "C:/Users/MBLONSKY/AppData/Local/Continuum/anaconda3/envs/AI/Scripts/helics-script.py", line 11, in <module>
    load_entry_point('helics-runner', 'console_scripts', 'helics')()
  File "C:\Users\MBLONSKY\AppData\Local\Continuum\anaconda3\envs\AI\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\MBLONSKY\AppData\Local\Continuum\anaconda3\envs\AI\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "C:\Users\MBLONSKY\AppData\Local\Continuum\anaconda3\envs\AI\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\MBLONSKY\AppData\Local\Continuum\anaconda3\envs\AI\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\MBLONSKY\AppData\Local\Continuum\anaconda3\envs\AI\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\mblonsky\documents\github\co-sim\src\helics-runner\helics_runner\cli.py", line 139, in run
    stderr=broker_o,
  File "C:\Users\MBLONSKY\AppData\Local\Continuum\anaconda3\envs\AI\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\MBLONSKY\AppData\Local\Continuum\anaconda3\envs\AI\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by akshaykj92** [comment]
@mnblonsky I have the same issue when I set broker=false, 
Traceback (most recent call last):
  File "c:\docs\anaconda_installation\envs\helics_tests\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\docs\anaconda_installation\envs\helics_tests\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Docs\anaconda_installation\envs\helics_tests\Scripts\helics.exe\__main__.py", line 7, in <module>
  File "c:\docs\anaconda_installation\envs\helics_tests\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\docs\anaconda_installation\envs\helics_tests\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\docs\anaconda_installation\envs\helics_tests\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\docs\anaconda_installation\envs\helics_tests\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\docs\anaconda_installation\envs\helics_tests\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\docs\anaconda_installation\envs\helics_tests\lib\site-packages\helics_cli\cli.py", line 184, in run
    stderr=broker_o,
  File "c:\docs\anaconda_installation\envs\helics_tests\lib\subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "c:\docs\anaconda_installation\envs\helics_tests\lib\subprocess.py", line 1017, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

However even with broker=true I get the following:
Error: Process broker has failed, killing other processes
Exception in thread Thread-1:
Traceback (most recent call last):
  File "c:\docs\anaconda_installation\envs\helics_tests\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "c:\docs\anaconda_installation\envs\helics_tests\lib\site-packages\helics_cli\status_checker.py", line 43, in run
    raise HELICSRuntimeError("Error has occurred")
helics_cli.exceptions.HELICSRuntimeError: Error has occurred

Any ideas, thanks!
